#!/usr/bin/env bash
# checks for uprgadeable packages

sudo apt-get update -qq
NUM=$(apt-get upgrade -s | grep -P '^\d+ upgraded' | cut -d" " -f1)

if [[ ${NUM} -eq 1 ]] ; then
    echo ${NUM} package upgradeable
else
    echo ${NUM} packages upgradeable
fi
