#!/bin/sh
# Start services if not running

if [ "`service ssh status | sed 's/.*not running.*/nok/'`" = "nok" ]
then
    sudo service ssh start
fi

if [ "`service docker status | sed 's/.*not running.*/nok/'`" = "nok" ]
then
    sudo service docker start
fi
